#ifndef MINI_PLAYER_100_H
# define MINI_PLAYER_100_H

static const char *mini_player_100_data = 
"/* XPM */\n"
"static char *result[] = {\n"
"/* columns rows colors chars-per-pixel */\n"
"\"24 24 4 1 \",\n"
"\"  c gray1\",\n"
"\". c #860000\",\n"
"\"X c #DC0000\",\n"
"\"o c black\",\n"
"/* pixels */\n"
"\"oooooooooooooooooooooooo\",\n"
"\"ooooooooo  ooooooooooooo\",\n"
"\"ooooooooo   oooooooooooo\",\n"
"\"oooooooo  .  ooooooooooo\",\n"
"\"oooooooo ...  oooooooooo\",\n"
"\"oooooooo ....  ooooooooo\",\n"
"\"ooooooo  ..... ooooooooo\",\n"
"\"ooooooo XXX.XX  oooooooo\",\n"
"\"ooooooo XXX.XXX  ooooooo\",\n"
"\"oooooo  XXX.XXXX  oooooo\",\n"
"\"oooooo XXXX.XXXXX  ooooo\",\n"
"\"oooooo XXXX.XXXXXX  oooo\",\n"
"\"ooooo  XXXX.XXXXXXX oooo\",\n"
"\"ooooo XXXXX.XXXXXXX  ooo\",\n"
"\"oooo  XXXXXX.XXXXXXX  oo\",\n"
"\"oooo XXXXXXX.XXXXXXXX  o\",\n"
"\"oooo XXXXXXX.XX        o\",\n"
"\"ooo  XXXX       oooooooo\",\n"
"\"ooo X     oooooooooooooo\",\n"
"\"ooo   oooooooooooooooooo\",\n"
"\"oooooooooooooooooooooooo\",\n"
"\"oooooooooooooooooooooooo\",\n"
"\"oooooooooooooooooooooooo\",\n"
"\"oooooooooooooooooooooooo\"\n"
"};\n"
;

#endif
