#ifndef MINI_PLAYER_180_H
# define MINI_PLAYER_180_H

static const char *mini_player_180_data = 
"/* XPM */\n"
"static char *result[] = {\n"
"/* columns rows colors chars-per-pixel */\n"
"\"24 24 6 1 \",\n"
"\"  c gray1\",\n"
"\". c gray7\",\n"
"\"X c #860000\",\n"
"\"o c #DC0000\",\n"
"\"O c gray91\",\n"
"\"+ c black\",\n"
"/* pixels */\n"
"\"++++++++++++++++++++++++\",\n"
"\"++++++++++++++++++++++++\",\n"
"\"++++++++++++++++  ++++++\",\n"
"\"++++++++++++++    ++++++\",\n"
"\"+++++++++++++  oo ++++++\",\n"
"\"+++++++++++   ooo ++++++\",\n"
"\"+++++++++   ooooo ++++++\",\n"
"\"+++++++   ooooooo ++++++\",\n"
"\"++++++   oooooooo ++++++\",\n"
"\"++++   oooooooooo ++++++\",\n"
"\"++   XXoooooooooo ++++++\",\n"
"\"O  XXXXXXXXXooooo ++++++\",\n"
"\"+ .XXXXoooooXXXXX ++++++\",\n"
"\"++   XXoooooooooo ++++++\",\n"
"\"++++   oooooooooo ++++++\",\n"
"\"++++++   oooooooo ++++++\",\n"
"\"++++++++  ooooooo ++++++\",\n"
"\"+++++++++   ooooo ++++++\",\n"
"\"+++++++++++   ooo ++++++\",\n"
"\"+++++++++++++  oo ++++++\",\n"
"\"++++++++++++++    ++++++\",\n"
"\"++++++++++++++++  ++++++\",\n"
"\"++++++++++++++++++++++++\",\n"
"\"++++++++++++++++++++++++\"\n"
"};\n"
;

#endif
