#ifndef MINI_PLAYER_360_H
# define MINI_PLAYER_360_H

static const char *mini_player_360_data = 
"/* XPM */\n"
"static char *result[] = {\n"
"/* columns rows colors chars-per-pixel */\n"
"\"24 24 4 1 \",\n"
"\"  c gray1\",\n"
"\". c #860000\",\n"
"\"X c #DC0000\",\n"
"\"o c black\",\n"
"/* pixels */\n"
"\"oooooooooooooooooooooooo\",\n"
"\"oooooooooooooooooooooooo\",\n"
"\"oooooo  oooooooooooooooo\",\n"
"\"oooooo    oooooooooooooo\",\n"
"\"oooooo XX  ooooooooooooo\",\n"
"\"oooooo XXX   ooooooooooo\",\n"
"\"oooooo XXXXX   ooooooooo\",\n"
"\"oooooo XXXXXXX   ooooooo\",\n"
"\"oooooo XXXXXXXXX  oooooo\",\n"
"\"oooooo XXXXXXXXXX   oooo\",\n"
"\"oooooo XXXXXXXXXX..   oo\",\n"
"\"oooooo ..............  o\",\n"
"\"oooooo XXXXXXXXXX...   o\",\n"
"\"oooooo XXXXXXXXXX..  ooo\",\n"
"\"oooooo XXXXXXXXX    oooo\",\n"
"\"oooooo XXXXXXX    oooooo\",\n"
"\"oooooo XXXXXXX  oooooooo\",\n"
"\"oooooo XXXXX   ooooooooo\",\n"
"\"oooooo XXX   ooooooooooo\",\n"
"\"oooooo X   ooooooooooooo\",\n"
"\"oooooo   ooooooooooooooo\",\n"
"\"oooooo  oooooooooooooooo\",\n"
"\"oooooooooooooooooooooooo\",\n"
"\"oooooooooooooooooooooooo\"\n"
"};\n"
;

#endif
