#ifndef PISNELO_H
# define PISNELO_H

static const char *pisnelo_data = 
"/* XPM */\n"
"static char *_a7562b36afa40b6f8597b8e0a5a4f28Zlv9A1X6Tum3IdQG[] = {\n"
"/* columns rows colors chars-per-pixel */\n"
"\"64 64 3 1 \",\n"
"\"   c #7AFF00\",\n"
"\".  c #000000\",\n"
"\"X c #070bff\",\n"
"/* pixels */\n"
"\"                                                                \",\n"
"\"                                                                \",\n"
"\"                                                                \",\n"
"\"                                                                \",\n"
"\"                                                                \",\n"
"\"                                                                \",\n"
"\"                                                                \",\n"
"\"                            XXXXXXXXXXX                         \",\n"
"\"                         XXXXXXXXXXXXXXXXX                      \",\n"
"\"                      XXXXXXXXXXXXXXXXXXXXXXX                   \",\n"
"\"                    XXXXXXXXXXXXXXXXXXXXXXXXXXX                 \",\n"
"\"                   XXXXXXXXXX.........XXXXXXXXXX                \",\n"
"\"                 XXXXXXXX.................XXXXXXXX              \",\n"
"\"                XXXXXXX.....................XXXXXXX             \",\n"
"\"               XXXXXX.........................XXXXXX            \",\n"
"\"              XXXXXX...........................XXXXXX           \",\n"
"\"             XXXXXX.............................XXXXXX          \",\n"
"\"            XXXXXX...............................XXXXXX         \",\n"
"\"            XXXXX.................................XXXXX         \",\n"
"\"           XXXXX...................................XXXXX        \",\n"
"\"          XXXXX.....................................XXXXX       \",\n"
"\"          XXXX.......................................XXXX       \",\n"
"\"         XXXXX.......XXXXXXXX..........XXXXXXX.......XXXXX      \",\n"
"\"         XXXX........XXXXXXXX..........XXXXXXX........XXXX      \",\n"
"\"         XXXX........XXXXXXXX..........XXXXXXX........XXXX      \",\n"
"\"        XXXX.........XXXXXXXX..........XXXXXXX.........XXXX     \",\n"
"\"        XXXX..........XXXX..............XXXX...........XXXX     \",\n"
"\"        XXXX..........XXXX..............XXXX...........XXXX     \",\n"
"\"       XXXXX...........................................XXXXX    \",\n"
"\"       XXXX.............................................XXXX    \",\n"
"\"       XXXX.............................................XXXX    \",\n"
"\"       XXXX.............................................XXXX    \",\n"
"\"       XXXX.............................................XXXX    \",\n"
"\"       XXXX.............................................XXXX    \",\n"
"\"       XXXX.............................................XXXX    \",\n"
"\"       XXXX..........XXXXXXXXXXXXXXXXXXXXXXXXXX.........XXXX    \",\n"
"\"       XXXX..........XXXX..XXXX.XXXX.XXXX..XXXX.........XXXX    \",\n"
"\"       XXXX..........XXXXX..XX..XXXX.XXXX..XXXX.........XXXX    \",\n"
"\"       XXXXX.........XXXXX..XX..XXXX...XX.XXXXX........XXXXX    \",\n"
"\"        XXXX..........XXXX..XX...XX...XXX.XXXXX........XXXX     \",\n"
"\"        XXXX..........XXXXX..X....X....X..XXXXX........XXXX     \",\n"
"\"        XXXX...........XXXX....X....X....XXXXX.........XXXX     \",\n"
"\"         XXXX..........XXXXX...XX...X...XXXXXX........XXXX      \",\n"
"\"         XXXX..........XXXXXX..XX..XXX..XXXXX.........XXXX      \",\n"
"\"         XXXXX..........XXXXX.XXXX.XXX..XXXXX........XXXXX      \",\n"
"\"          XXXX..........XXXXXXXXXXXXXXXXXXXX.........XXXX       \",\n"
"\"          XXXXX...........XXXXXXXXXXXXXXXXX.........XXXXX       \",\n"
"\"           XXXXX.............XXXXXXXXXXXXX.........XXXXX        \",\n"
"\"            XXXXX..............XXXXXXXXXX.........XXXXX         \",\n"
"\"            XXXXXX...............................XXXXXX         \",\n"
"\"             XXXXXX.............................XXXXXX          \",\n"
"\"              XXXXXX...........................XXXXXX           \",\n"
"\"               XXXXXX.........................XXXXXX            \",\n"
"\"                XXXXXXX.....................XXXXXXX             \",\n"
"\"                 XXXXXXXX.................XXXXXXXX              \",\n"
"\"                   XXXXXXXXXX.........XXXXXXXXXX                \",\n"
"\"                    XXXXXXXXXXXXXXXXXXXXXXXXXXX                 \",\n"
"\"                      XXXXXXXXXXXXXXXXXXXXXXX                   \",\n"
"\"                         XXXXXXXXXXXXXXXXX                      \",\n"
"\"                            XXXXXXXXXXX                         \",\n"
"\"                                                                \",\n"
"\"                                                                \",\n"
"\"                                                                \",\n"
"\"                                                                \"\n"
"};\n"
;

#endif
